Created a method that extracts data as list of dictionaries from data validator.
jTaylo99/kolumnextractor pull request #35
Opened 2022-10-30 23:46 UTC by bissella

Created a method that extracts data as list of dictionaries from data validator.

2022-10-30 23:50 UTC, jTaylo99 requested changes
Only minor changes needed.

2022-10-30 23:50 UTC, jTaylo99 commented on data/test.csv
> +column 1,column 2,column 31,2,33,4,5
Leftover changes from testing csv

2022-10-30 23:50 UTC, jTaylo99 commented on src/data_holder.py
> +    def all_data_to_dict(self):
Docstring would be good here

2022-10-31 00:02 UTC, jTaylo99 approved these changes
Looks good

2022-10-31 00:02 UTC, bissella commented
Made minor changes.

2022-10-31 00:02 UTC, merged